### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by eperdeme** [tcpcloud/python-aptly#2]
Hello,

Do you have any examples of this method working with Ubuntu multi component repos and maybe a link to the CI / script that produces the snapshots. 

The end result should be the same structure as a normal ubuntu miror with dist-updates/{main,universe} dist(main,universe}

I guess the config would look something like the below? Would that keep the components separate when published ?

`mirror:
  ubuntu-trusty-main:
    component: main
    distributions:
      - nightly/trusty

  ubuntu-trusty-universe:
    component: universe
    distributions:
      - nightly/trusty

  ubuntu-trusty-security-main:
    component: main
    distributions:
      - nightly/trusty-security

  ubuntu-trusty-security-universe:
    component: universe
    distributions:
      - nightly/trusty-security

  ubuntu-trusty-updates-main:
    component: main
    distributions:
      - nightly/trusty-updates

  ubuntu-trusty-updates-universe:
    component: universe
    distributions:
      - nightly/trusty-updates
`

**Comment by fpytloun** [comment]
Hello,

this is setup that will create exactly same publish (with all components) as official Ubuntu repositories:

```
mirror:
  # Main repository
  ubuntu-trusty-main:
    component: main
    distributions:
      - trusty
  ubuntu-trusty-universe:
    component: universe
    distributions:
      - trusty
  ubuntu-trusty-multiverse:
    component: multiverse
    distributions:
      - trusty
  ubuntu-trusty-restricted:
    component: restricted
    distributions:
      - trusty

  # Updates
  ubuntu-trusty-updates-main:
    component: main
    distributions:
      - trusty-updates
  ubuntu-trusty-updates-universe:
    component: universe
    distributions:
      - trusty-updates
  ubuntu-trusty-updates-multiverse:
    component: multiverse
    distributions:
      - trusty-updates
  ubuntu-trusty-updates-restricted:
    component: restricted
    distributions:
      - trusty-updates

  # Security
  ubuntu-trusty-security-main:
    component: main
    distributions:
      - trusty-security
  ubuntu-trusty-security-universe:
    component: universe
    distributions:
      - trusty-security
  ubuntu-trusty-security-multiverse:
    component: multiverse
    distributions:
      - trusty-security
  ubuntu-trusty-security-restricted:
    component: restricted
    distributions:
      - trusty-security
```

You can also use prefix in publishes, in that case use:

```
distributions:
  - nightly/trusty-security
```

Then you will reference your mirror like this:
`http://apt.mydomain.tld/nightly/ trusty-security main universe multiverse restricted`

instead of

`http://apt.mydomain.tld/ trusty-security main universe multiverse restricted`
